### ISSUE TITLE
Repository not found.

### ISSUE THREAD

**Issue by Flerndip** [lifeisboringsoprogramming/sd-webui-lookbook#1]
remote: Repository not found.
    fatal: repository 'https://github.com/lifeisboringsoprogramming/sd-webui-img2lookbook.git/' not found
    '

git opens its login dialog when this happens

**Comment by lifeisboringsoprogramming** [comment]
```
git clone https://github.com/lifeisboringsoprogramming/sd-webui-lookbook.git
```

**Comment by Flerndip** [comment]
So are you suggesting using the standalone version for now?  I had tried installing it in auto1111 but ran into the above issues.

**Comment by lifeisboringsoprogramming** [comment]
I can install in Web UI

![image](https://github.com/lifeisboringsoprogramming/sd-webui-lookbook/assets/119839123/6b067cf7-44da-46a3-adb8-cd8a8ea5d0f7)

**Comment by Flerndip** [comment]
Confirmed, this new link worked for me in the a1111 Install-From-URL.  The one I initially copy-pasted from the install instructions did not. 
 Thanks for making this!

**Comment by Flerndip** [comment]
If you added a face-tracking feature to achieve more of a Ken Burns zoom effect, I would have little choice but to get on the Patreon.

**Comment by lifeisboringsoprogramming** [comment]
thanks for the suggestion, I can look into it.

**Comment by Flerndip** [comment]
Thanks, and if you're taking suggestions you might add an option to fit the per-image duration to be derived from a user-entered BPM value, if the user happens to know the **beats per minute** of the track they are using, so that the image changes can seem in sync with the audio track.  Of course a lot of music has variable BPM but many tracks can be quantized for beat matching.  Anyway I hope you keep up the excellent work!

**Comment by Flerndip** [comment]
As for the face-tracking feature I'm not even talking about anything more sophisticated than using controlnet to locate the largest face in the image and move the zoom-in coordinates to that location.

**Comment by lifeisboringsoprogramming** [comment]
thanks again for the suggestion
